global:
  resolve_timeout: 5m
 

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: email_alert
receivers:
- name: email_alert
  email_configs:
  - to: csemanit2015@gmail.com
    from: aryan.arunachalam@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: aryan.arunachalam@gmail.com
    auth_identity: aryan.arunachalam@gmail.com
    auth_password: qzqyqmbeymmjtbbk
